### ISSUE TITLE
Issue with 'find'

### ISSUE THREAD

**Issue by Trid-collab** [gelguy/wilder.nvim#129]
I stumbled upon this while looking for an alternate to cmp cmdline.
I have an issue which I need help . While I am using the `find` cmd at the root of the project it doesn't seem to search for the files in the sub dirs. While this works perfectly if I use `find` without `wilder`. The `edit` cmd works just fine with the plugin going down the project sub dir.

Lastly have noticed that if I change a project using the `telescope project` plugin the dir for the `find' and others doesn't change and is still in the first project dir.

I am using the latest neovim nightly

**Comment by gelguy** [comment]
Thanks for the bug report!

Can I check if you have `set path=**`? I don't handle this case for `:find` currently, will be working on it.

For `:edit`, `wilder#python_file_finder_pipeline()` is providing the sub-directory searching, and only works for `:e`, `:cd` or other commands with `file` expansions.

**Comment by gelguy** [comment]
I've pushed a9ea0c69b37850752d5f8431b7be6bf8f1a0254c, could you help check if the latest `master` fixes your issue?

**Comment by Trid-collab** [comment]
Thank you for the quick revert.

> Can I check if you have `set path=**`?
Yes, I do have that set. I guess that's `find` works like I mentioned normally without wilder.

The new master fixes the problem but the second issue still remains. 

`if I change a project using the telescope project plugin the dir for the `find' and others doesn't change and is still in the first project dir when I use wilder.`

This doesn't happen when I don't use wilder .When I use `find` or `edit` command without wilder , they search the present project dir to which I had jumped using the Project plugin and not the 1st project. In fact it searches file depending upon the file open in the buffer depending on which project it belongs

**Comment by gelguy** [comment]
I've tested `wilder` with `telescope-project` and have found no issues with the directory switching.

Do you have `'autochdir`' set? You can check if it is set with `:set autochdir?` If you do, then the issue is related to #62. `telescope-project` works fine without `autochdir`, so it might be better to turn `autochdir` off.

Otherwise could you provide a minimal `init.vim`/`init.lua` for me to reproduce the issue? Providing the Neovim version from `:version` would help too.

**Comment by Trid-collab** [comment]
I have checked the `autochdir`, its not set. But the issue persists . I am using `project.nvim` with `telescope`.. For some reason it works with `cmpcmdline` and also if only use the` :find` without any this plugin.

**Comment by gelguy** [comment]
I've managed to reproduce this. `wilder` was not handling `cwd` correctly after the directory was changed by `project.nvim`.

Can you pull the latest master and check if e3880f3eb8970fc49fbb8957373f730b3c70fa29 fixes this for you? Thanks!

**Comment by gelguy** [comment]
I've pushed 777b163e394ba658ef288292efb533b25610ef9d which now shows the file paths relative to the current directory, as well as improve performance by a little. The output result may differ slightly from Neovim's default `:find` but I think the output is still in line with user expectations. (There's no specification for `:find` so it is difficult to reproduce Neovim/Vim's exact behavior).

For fuzzy finding, I strongly recommend using `:e` together with `wilder#python_file_finder_pipeline()` instead of `:find` since the file finder can use `ripgrep` or `fd` which makes performance significantly faster.
