### ISSUE TITLE
Search and replace flicker highlight

### ISSUE THREAD

**Issue by argapost** [gelguy/wilder.nvim#83]
Hello,

When I try to search and replace using `:%spattern/testg` the highlight of the pattern flickers as you can see in the following video:

https://user-images.githubusercontent.com/58076098/133088146-9de93150-d147-4e93-832e-28b8d6626da8.mp4

If I disable wilder.vim I don't have this problem. Thank you in advance for your help.

**Comment by gelguy** [comment]
Could you help paste the output of `:version` here?

Assuming you use Neovim, this is similar to #30 which is fixed by https://github.com/neovim/neovim/pull/15380. Can you check if the latest Neovim nightly fixes this?

More generally, `wilder#substitute_pipeline()` doesn't work well in Neovim. https://github.com/neovim/neovim/issues/9777 disables `redraw`-ing while in `inccommand` so the floating windows don't render correctly. I'll consider removing it from the example config in the README.

**Comment by argapost** [comment]
Ah, I see yeah I have the neovim release 0.5 because the nightly doesn't work well with some other plugins.
I deleted the `wilder#substitute_pipeline()` section but still the same issue. I guess the only solution is to update to the nightly right?

**Comment by gelguy** [comment]
This shouldn't happen when the `wilder#substitute_pipeline()` is removed. Just to check - are you using the latest version of `wilder.nvim`?

**Comment by argapost** [comment]
yes I :PackerSync, :PackerCompile

**Comment by gelguy** [comment]
Ah, I think I know the problem - `inccommand` is disabled and I only apply the workaround for `/` mode.

Setting `'hide_in_substitute' : 1` in `wilder#cmdline_pipeline()` should solve the issue. Remember to remove `wilder#substitute_pipeline()` as well.
```vim
call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     ... other pipelines ...
      \     wilder#cmdline_pipeline({
      \       ... other options ...
      \       'hide_in_substitute': 1,
      \     }),
      \     ... other pipelines ...
      \ ])
```

**Comment by argapost** [comment]
Yeap it worked thanks!
